### ISSUE TITLE
change IP address and port of vst version

### ISSUE THREAD

**Issue by timpauli** [keijiro/rust-zmq-test#2]
Hi,

is there the possibility to change the IP address and port in the vst version?

Thank a lot

**Comment by keijiro** [comment]
Do you mean that you want to change the IP/port# on the VST UI?

That's technically possible, but I wouldn't like to do it because I'm not a VST expert -- Adding a good GUI to a VST is not an easy task.

Please understand that I intentionally cut this kind of luxury to reduce the development cost.

**Comment by keijiro** [comment]
I close this issue now. Please reopen it for further problems.
